version: 2.1

# -------------------------
#        ORBS
# -------------------------
orbs:
  nx: nrwl/nx@1.6.1
  rust: circleci/rust@1.6.0
  browser-tools: circleci/browser-tools@1.4.6

# -------------------------
#        EXECUTORS
# -------------------------

defaults: &defaults
  working_directory: ~/repo

executors:
  linux:
    <<: *defaults
    docker:
      - image: cimg/rust:1.73.0-browsers
    resource_class: medium+

  macos:
    <<: *defaults
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: '14.2.0'

# -------------------------
#        COMMANDS
# -------------------------
commands:
  run-pnpm-install:
    parameters:
      os:
        type: string
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - node-deps-{{ arch }}-v3-{{ checksum "pnpm-lock.yaml" }}
      - when:
          condition:
            equal: [<< parameters.os >>, linux]
          steps:
            - run:
                name: Install pnpm package manager (linux)
                command: |
                  npm install --prefix=$HOME/.local -g @pnpm/exe@8.7.4
      - when:
          condition:
            equal: [<< parameters.os >>, macos]
          steps:
            - run:
                name: Install pnpm package manager (macos)
                command: |
                  npm install -g @pnpm/exe@8.7.4
      - run:
          name: Install Dependencies
          command: |
            pnpm install --frozen-lockfile
            pnpm playwright install --with-deps firefox webkit chrome
      - save_cache:
          name: Save pnpm Package Cache
          key: node-deps-{{ arch }}-v3-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
            - ~/.cache/Cypress
            - node_modules
# -------------------------
#          JOBS
# -------------------------
jobs:
  # -------------------------
  #     JOBS: Main Linux
  # -------------------------
  main-linux:
    executor: linux
    environment:
      NX_E2E_CI_CACHE_KEY: e2e-circleci-linux
      NX_VERBOSE_LOGGING: 'true'
      NX_DAEMON: 'true'
      NX_PERF_LOGGING: 'false'
      NX_NATIVE_LOGGING: 'false'
      NX_E2E_RUN_E2E: 'true'
      NX_CI_EXECUTION_ENV: 'linux'
    steps:
      - run: lscpu
      - checkout
      - run: npx nx-cloud@next start-ci-run --distributes-on="8 linux-medium" --stop-agents-after="e2e"
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y ca-certificates lsof
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run-pnpm-install:
          os: linux
      - nx/set-shas:
          main-branch-name: 'master'
      - run:
          name: Benchmark
          command: node benchmark.js
          no_output_timeout: 20m

# -------------------------
#        WORKFLOWS(JOBS)
# -------------------------
workflows:
  version: 2

  build:
    jobs:
      - main-linux
